### ISSUE TITLE
getting errors

### ISSUE THREAD

**Issue by Legend-of-Success** [dmytrostriletskyi/django-telegram-login#13]
Hi.
I tried to use this package but I am continously getting this error!
`Internal Server Error: /
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/lib/python3.5/site-packages/django/utils/deprecation.py", line 97, in __call__
    response = self.process_response(request, response)
  File "/usr/lib/python3.5/site-packages/django/middleware/clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'bool' object has no attribute 'get'
`

**Comment by dmytrostriletskyi** [comment]
@Legend-of-Success, hello, seems you return something weird from view. Could you provide a peace of code you get the error at?
